<div class="field<?php if (!$this->isFieldValid()): ?> has-error has-feedback<?php endif; ?>">
	
	<label for="<?php echo $this->getFieldHtmlId(); ?>">
		<?php echo $this->getField()->getTitle(); ?>
	</label>
	
	<?php echo $this->renderInput(); ?>

	<?php if (!$this->isFieldValid()): ?>
		<small class="text-danger">
			<?php foreach ($this->getFieldErrors() as $error): ?>
				<?php echo __($error->getMessage()); ?>
			<?php endforeach; ?>
        </small> 
	<?php endif; ?>
</div>