<?php
	$form = $block->getForm();
?>
<form method="post" id="etailors-form-<?php echo $form->getId(); ?>" action="<?php echo $block->getPostUrl(); ?>" enctype="multipart/form-data">
	<?php echo $block->getChildHtml('etailors_forms_form_before') ?>
	<div class="container">
		<div class="row">
			<?php echo $block->getContent(); ?>	
		</div>
		<?php echo $block->getChildHtml('etailors_forms_form_after') ?>
		<div class="row">
			<div class="col-xs-12">
				<?php if ($this->displaySubmitButton()): ?>
					<?php if ($this->displayPreviousButton()): ?>
						<div class="pull-left">
							<a href="<?php echo $block->getPreviousPageUrl(); ?>">
								<span><?php echo __('Previous page'); ?></span>
							</a>
						</div>
					<?php endif; ?>
					<div class="pull-right">
						<button type="submit" class="btn btn-theme">
							<span><?php echo __('Submit'); ?></span>
						</button>
					</div>
				<?php else: ?>
					<?php if ($this->displayPreviousButton()): ?>
						<div class="pull-left">
							<a href="<?php echo $block->getPreviousPageUrl(); ?>">
								<span><?php echo __('Previous page'); ?></span>
							</a>
						</div>
					<?php endif; ?>
					<div class="pull-right">
						<button type="submit" name="new_page" value="<?php echo $this->getNextPage(); ?>" class="btn btn-theme">
							<span><?php echo __('Next page'); ?></span>
						</button>
					</div>
				<?php endif; ?>
			</div>
		</div>
		<?php echo $block->getChildHtml('etailors_forms_form_after_submit') ?>
	</div>	
</form>