<?php $iterator = 0; ?>
<div class="checkbox-wrapper" data-field-id="<?php echo $this->getField()->getId(); ?>">
    <?php foreach ($this->getOptions() as $option): ?>
	    <div class="checkbox-field-value">
		    <input type="checkbox" 
			    name="<?php echo $this->getFieldName(); ?>[]" 
			    id="<?php echo $this->getFieldHtmlId(); ?>_<?php echo $iterator; ?>"
			    class="<?php echo $this->getFieldClasses(); ?>"
			    value="<?php echo $option; ?>">
		    <label class="checkbox-field-label" for="<?php echo $this->getFieldHtmlId(); ?>_<?php echo $iterator; ?>">
			    <?php echo $option; ?>
		    </label>
	    </div>
	    <?php $iterator++; ?>
    <?php endforeach; ?>
</div>
