<select
	name="<?php echo $this->getFieldName(); ?>" 
	id="<?php echo $this->getFieldHtmlId(); ?>"
	class="<?php echo $this->getFieldClasses(); ?>"
	data-validate="<?php echo $this->getJsValidation(); ?>"
	data-field-id="<?php echo $this->getField()->getId(); ?>">
	
	<?php foreach ($this->getOptions() as $option): ?>
		<option value="<?php echo $option; ?>"
				<?php echo ($this->getValue() == $option) ? ' selected="selected"' : ''; ?>>
				<?php echo $option; ?>
		</option>
	<?php endforeach; ?>
</select>
